{
    'name': 'Transport Logistics Management',
    'version': '1.0.123',
    'category': 'Transport',
    'summary': '3PL Transport Management System',
    'description': '''
        3PL Transport Module - CMR/ADR/T1 compliance
        Freight transport planning, dispatch, POD, and billing.
    ''',
    'author': 'TLM Team',
    'depends': [
        'base', 'mail', 'stock', 'account',
        'portal', 'contacts', 'product', 'fleet',
        'worlddepot',
    ],
    'data': [
        'data/transport_type_data.xml',
        'data/carrier_service_data.xml',
        'data/transport_un_dictionary_data.xml',
        'security/security.xml',
        'security/security_settlement_groups.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/surcharge_data.xml',
        'data/transport_scene_data.xml',
        'data/workflow_guard_data.xml',
        'data/transport_event_code_data.xml',
        'data/transport_charge_item_data.xml',
        'data/business_matrix_data.xml',
        'views/tlmp_menu_groups.xml',
        'views/pickup_plan_views.xml',
        'views/transport_request_views.xml',
        'views/transport_inquiry_views.xml',
        'views/transport_quote_views.xml',
        'views/transport_order_views.xml',
        'views/transport_container_views.xml',
        'views/surcharge_views.xml',
        'views/transport_tracking_views.xml',
        'views/transport_workflow_views.xml',
        'views/transport_dashboard_views.xml',
        'views/transport_report_views.xml',
        'views/pod_views.xml',
        'views/cmr_views.xml',
        'views/cmr_coordinate_views.xml',
        'views/transport_tracking_views.xml',
        'views/transport_dashboard_views.xml',
        'views/transport_report_views.xml',
        'views/customer_bill_views.xml',
        'views/carrier_settlement_views.xml',
        'views/pricing_rule_views.xml',
        'views/portal_customer_templates.xml',
        'views/portal_carrier_templates.xml',
        'reports/report_cmr.xml',
        'reports/report_adr.xml',
        'reports/report_bill.xml',
        'views/container_service_views.xml',
        'views/container_master_views.xml',
        'views/transport_plan_views.xml',
        'views/schedule_calendar_views.xml',
        'views/transport_fee_views.xml',
        'views/transport_un_dictionary_views.xml',
        'views/transport_dgd_views.xml',
        'views/transport_type_views.xml',
        'data/transport_charge_type_data.xml',
        'views/carrier_service_views.xml',
        'views/transport_shipment_label_views.xml',
        'views/transport_carrier_charge_type_views.xml',
        'views/transport_carrier_billing_views.xml',
        'views/transport_carrier_allocation_views.xml',
        'views/transport_reference_views.xml',
        'views/transport_carrier_profile_views.xml',
        'views/transport_carrier_batch_views.xml',
        'views/transport_carrier_case_views.xml',
        'views/transport_carrier_adjustment_views.xml',
        'views/transport_carrier_invoice_template_views.xml',
        'views/transport_carrier_invoice_import_views.xml',
        'views/transport_settlement_exception_views.xml',
        'views/settlement_export_wizard.xml',
        'views/transport_match_rule_views.xml',
        'views/transport_scene_views.xml',
        'views/business_matrix_views.xml',
        'views/pickup_schedule_templates.xml',
        'views/product_adr_views.xml',
        'views/tlmp_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
                'wd_tlms/static/src/js/pickup_schedule.js',
                'wd_tlms/static/src/js/tlmp_portal_carrier.js',
                'wd_tlms/static/src/js/tlmp_portal_customer.js',
                'wd_tlms/static/src/js/tlmp_portal_helper.js',
                'wd_tlms/static/src/css/pickup_schedule.css',
                'wd_tlms/static/src/xml/transport_plan.xml',
            ]
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
