from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError
import logging
import base64
from cryptography.fernet import Fernet, InvalidToken

_logger = logging.getLogger(__name__)

class DeviceCertBind(models.Model):
    """Master model for Device-Certificate Binding"""
    _name = 'device.cert.bind'
    _description = 'Device-Certificate Binding'
    _order = 'create_date DESC'
    _sql_constraints = [
        ('cert_serial_unique', 'UNIQUE(cert_serial)', 'Certificate serial number must be unique.'),
        ('device_cert_unique', 'UNIQUE(device_id, cert_serial)', 'The binding between device and certificate must be unique.'),
    ]

    # ========== Core Fields ==========
    device_id = fields.Char(
        string='Device Fingerprint',
        required=False,  # Allowed to be empty for placeholder records
        index=True,
        help='Unique device fingerprint generated by the browser. Empty means waiting for first binding.'
    )

    cert_serial = fields.Char(
        string='Certificate Serial Number',
        required=True,
        index=True,
        help='Unique serial number of the SSL certificate.'
    )

    user_email = fields.Char(
        string='User Email',
        help='Email address of the user associated with the certificate.'
    )

    ip_address = fields.Char(
        string='IP Address',
        help='Last recorded network address.'
    )

    create_date = fields.Datetime(
        string='Creation Date',
        default=fields.Datetime.now
    )

    update_date = fields.Datetime(
        string='Last Updated',
        default=fields.Datetime.now,
        compute='_compute_update_date',
        store=True
    )

    # ========== Certificate File Fields ==========
    cert_file = fields.Binary(
        string='Certificate File (.p12)',
        attachment=True,
        help='Certificate file in PKCS#12 format.'
    )

    cert_filename = fields.Char(
        string='Filename',
        help='Original filename of the certificate file.'
    )

    # ========== Encrypted Password Fields ==========
    password_encrypted = fields.Char(
        string='Encrypted Password',
        help='Certificate password stored using AES encryption.'
    )

    # Password viewing audit fields
    password_last_viewed = fields.Datetime(
        string='Password Last Viewed'
    )

    password_viewed_by = fields.Many2one(
        'res.users',
        string='Last Viewed By'
    )

    # ========== Status Management Fields ==========
    state = fields.Selection([
        ('draft', 'To Activate'),
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('revoked', 'Revoked')
    ],
    string='Status',
    default='draft',
    required=True,
    index=True
    )

    is_placeholder = fields.Boolean(
        string='Is Placeholder',
        compute='_compute_is_placeholder',
        store=True,
        help='True indicates this record is waiting for first binding.'
    )

    # ========== Related Fields ==========
    mail_log_ids = fields.One2many(
        'device.cert.mail.log',
        'bind_id',
        string='Mail Send Logs'
    )

    status_log_ids = fields.One2many(
        'device.cert.status.log',
        'bind_id',
        string='Status Change Logs'
    )
    last_login=fields.Datetime(string='Last Login')

    # ========== Computed Fields ==========
    @api.depends('device_id')
    def _compute_is_placeholder(self):
        """Compute whether the record is a placeholder."""
        for record in self:
            record.is_placeholder = not record.device_id or record.device_id == 'PLACEHOLDER_FOR_FIRST_BIND'

    @api.depends('state')
    def _compute_update_date(self):
        """Update the modification date when the state changes."""
        for record in self:
            if record._origin.state != record.state:
                record.update_date = fields.Datetime.now()

    # ========== Constraint Validation ==========
    @api.constrains('cert_serial')
    def _check_cert_serial_format(self):
        """Validate the format of the certificate serial number."""
        for record in self:
            if record.cert_serial and len(record.cert_serial) < 10:
                raise ValidationError(_("Certificate serial number format is incorrect."))

    @api.constrains('device_id')
    def _check_device_id_uniqueness(self):
        """Validate the uniqueness of the Device ID (for non-placeholder cases)."""
        for record in self:
            if record.device_id and record.device_id != 'PLACEHOLDER_FOR_FIRST_BIND':
                existing = self.search([
                    ('device_id', '=', record.device_id),
                    ('id', '!=', record.id)
                ], limit=1)
                if existing:
                    raise ValidationError(
                        _("Device ID %s is already bound to another certificate.") % record.device_id
                    )

    # ========== Key Management Methods ==========

    def _get_encryption_key(self):
        """Get the encryption key (consistent with the API controller)."""
        config_param = self.env['ir.config_parameter'].sudo()
        key_b64 = config_param.get_param('custom_device_cert.encryption_key')

        if not key_b64:
            # Automatically generate a new key
            new_key = Fernet.generate_key()
            key_b64 = base64.urlsafe_b64encode(new_key).decode()
            config_param.set_param('custom_device_cert.encryption_key', key_b64)
            _logger.info("New encryption key has been generated.")

        return base64.urlsafe_b64decode(key_b64.encode())

    # ========== Password Encryption/Decryption Methods ==========

    def _encrypt_password(self, plain_password):
        """Encrypt a password (using the same logic as the API controller)."""
        if not plain_password:
            return None

        try:
            key = self._get_encryption_key()
            cipher = Fernet(key)
            encrypted = cipher.encrypt(plain_password.encode())
            return base64.b64encode(encrypted).decode()
        except Exception as e:
            _logger.error(f"Password encryption failed: {e}")
            raise UserError(_("Password encryption failed: %s") % str(e))

    def _decrypt_password_old(self, encrypted_password_b64):
        """Decrypt a password."""
        if not encrypted_password_b64:
            return None

        try:
            encrypted = base64.b64decode(encrypted_password_b64.encode())
            key = self._get_encryption_key()
            cipher = Fernet(key)
            decrypted = cipher.decrypt(encrypted)
            return decrypted.decode()
        except InvalidToken:
            _logger.error("Password decryption failed: Invalid encryption token.")
            raise UserError(_("Password decryption failed. The encryption key may have changed or the data is corrupted."))
        except Exception as e:
            _logger.error(f"Password decryption failed: {e}")
            raise UserError(_("Password decryption failed: %s") % str(e))
        
    # 在 device_bind.py 中修改 _decrypt_password 方法
    def _decrypt_password(self, encrypted_password):
        """解密密码 - 修复版本"""
        if not encrypted_password:
            return None
        
        try:
            # 首先确保是有效的base64字符串
            encrypted_password = encrypted_password.strip()
            
            # 如果长度不是4的倍数，添加填充字符
            if len(encrypted_password) % 4 != 0:
                padding = 4 - (len(encrypted_password) % 4)
                encrypted_password += '=' * padding
            
            # 解码base64
            encrypted_bytes = base64.b64decode(encrypted_password)
            
            # 使用Fernet解密
            from cryptography.fernet import Fernet
            key = self._get_encryption_key()
            cipher = Fernet(key)
            decrypted_bytes = cipher.decrypt(encrypted_bytes)
            
            return decrypted_bytes.decode('utf-8')
        except Exception as e:
            _logger.error(f"Password decryption failed: {e}")
            # 返回占位符而不是抛出异常
            return "[Password decryption error]"    

    # ========== Business Methods ==========

    def action_send_certificate_old(self):
        """Send the certificate via email (with the certificate file attached)."""
        self.ensure_one()

        if not all([self.user_email, self.cert_file]):
            raise UserError(_("Cannot send email: Missing recipient email or certificate file."))

        # Find the email template
        template = self.env.ref('custom_device_cert.email_template_cert_guide', False)
        if not template:
            raise UserError(_("Email template not found."))

        # Create the certificate attachment
        attachment = self.env['ir.attachment'].create({
            'name': self.cert_filename or f'certificate_{self.cert_serial[:8]}.p12',
            'datas': self.cert_file,
            'res_model': 'device.cert.bind',
            'res_id': self.id,
            'type': 'binary',
        })

        # Send the email
        try:
            template.with_context(attachment_ids=[attachment.id]).send_mail(
                self.id,
                force_send=True
            )

            # Log the email sending
            self.env['device.cert.mail.log'].create({
                'bind_id': self.id,
                'email': self.user_email,
                'sent_by': self.env.user.id,
            })

            _logger.info(f"Certificate email has been sent to {self.user_email}.")

        except Exception as e:
            _logger.error(f"Failed to send email: {e}")
            raise UserError(_("Failed to send email: %s") % str(e))

    def action_send_certificate(self):
        """Send the certificate via email (simplified)"""
        self.ensure_one()

        if not self.user_email:
            raise UserError(_("Recipient email is missing."))

        try:
            # Create simple email directly
            mail_values = {
                'subject': 'Your Device Certificate',
                'body_html': """<p>Dear User,</p><p>Your certificate is ready.</p>""",
                'email_to': self.user_email,
                'auto_delete': True,
            }
            mail = self.env['mail.mail'].create(mail_values)
            mail.send()

            _logger.info("Email sent successfully to %s", self.user_email)
            return True

        except Exception as e:
            _logger.error("Send email failed: %s", str(e))
            raise UserError(_("Failed to send email: %s", str(e)))
    def action_view_password(self):
        """Securely view the password (requires administrator privileges)."""
        self.ensure_one()

        if not self.env.user.has_group('base.group_system'):
            raise UserError(_("Insufficient permissions. Administrator rights are required."))

        if not self.password_encrypted:
            raise UserError(_("This record does not have a stored certificate password."))

        # Decrypt the password
        try:
            password = self._decrypt_password(self.password_encrypted)
        except UserError as e:
            raise e
        except Exception as e:
            raise UserError(_("Password decryption failed."))

        # Record audit log
        self.write({
            'password_last_viewed': fields.Datetime.now(),
            'password_viewed_by': self.env.user.id
        })

        # Return a wizard for viewing the password
        return {
            'type': 'ir.actions.act_window',
            'name': _('Certificate Password'),
            'res_model': 'device.cert.bind.password.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_password': password,
                'default_bind_id': self.id,
            }
        }

    def action_activate(self):
        """Activate the binding."""
        for record in self:
            if record.state != 'active':
                old_state = record.state
                record.state = 'active'

                # Log the status change
                self.env['device.cert.status.log'].create({
                    'bind_id': record.id,
                    'old_state': old_state,
                    'new_state': 'active',
                    'done_by': self.env.user.id,
                })
                _logger.info(f"Binding record {record.id} has been activated.")

    def action_deactivate(self):
        """Deactivate the binding."""
        for record in self:
            if record.state != 'inactive':
                old_state = record.state
                record.state = 'inactive'

                self.env['device.cert.status.log'].create({
                    'bind_id': record.id,
                    'old_state': old_state,
                    'new_state': 'inactive',
                    'done_by': self.env.user.id,
                })
                _logger.info(f"Binding record {record.id} has been deactivated.")

    def action_revoke(self):
        """Revoke the binding (irreversible operation)."""
        self.ensure_one()

        if self.state == 'revoked':
            raise UserError(_("This binding is already revoked."))

        old_state = self.state
        self.state = 'revoked'

        self.env['device.cert.status.log'].create({
            'bind_id': self.id,
            'old_state': old_state,
            'new_state': 'revoked',
            'done_by': self.env.user.id,
            'notes': 'Certificate has been permanently revoked.'
        })

        _logger.warning(f"Binding record {self.id} has been revoked.")

    # ========== Utility Methods ==========

    def find_by_device_and_cert(self, device_id, cert_serial):
        """Find the exact device-certificate binding."""
        return self.search([
            ('device_id', '=', device_id),
            ('cert_serial', '=', cert_serial)
        ], limit=1)

    def find_placeholder_by_cert(self, cert_serial):
        """Find a placeholder record for the specified certificate serial number."""
        return self.search([
            ('cert_serial', '=', cert_serial),
            '|', ('device_id', '=', False),
                 ('device_id', '=', 'PLACEHOLDER_FOR_FIRST_BIND')
        ], limit=1)


class DeviceCertMailLog(models.Model):
    """Sub-model for Mail Sending Logs"""
    _name = 'device.cert.mail.log'
    _description = 'Mail Send Logs'
    _order = 'create_date DESC'

    bind_id = fields.Many2one(
        'device.cert.bind',
        string='Binding Record',
        ondelete='cascade',
        required=True
    )
    email = fields.Char(string='Recipient Email', required=True)
    sent_by = fields.Many2one('res.users', string='Sent By')
    create_date = fields.Datetime(string='Sent On', default=fields.Datetime.now)
    status = fields.Selection([
        ('sent', 'Sent'),
        ('failed', 'Failed')
    ], string='Status', default='sent')


class DeviceCertStatusLog(models.Model):
    """Sub-model for Status Change Logs"""
    _name = 'device.cert.status.log'
    _description = 'Status Change Logs'
    _order = 'create_date DESC'

    bind_id = fields.Many2one(
        'device.cert.bind',
        string='Binding Record',
        ondelete='cascade',
        required=True
    )
    old_state = fields.Char(string='Previous State')
    new_state = fields.Char(string='New State', required=True)
    done_by = fields.Many2one('res.users', string='Operator')
    create_date = fields.Datetime(string='Operation Time', default=fields.Datetime.now)
    notes = fields.Text(string='Notes')