from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError
import logging
import re

_logger = logging.getLogger(__name__)
def is_valid_email(email):
    return re.match(r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email) is not None

class DeviceCertBind(models.Model):
    """Master model for Device-Certificate Binding"""
    _name = 'device.cert.bind'
    _description = 'Device-Certificate Binding'
    _order = 'create_date DESC'
    _sql_constraints = [
        ('cert_serial_unique', 'UNIQUE(cert_serial)', 'Certificate serial number must be unique.'), 
    ]

    # ========== Core Fields ==========
    device_id = fields.Char(
        string='Device Fingerprint',
        required=False,  # Allowed to be empty for placeholder records
        index=True,
        help='Unique device fingerprint generated by the browser. Empty means waiting for first binding.'
    )

    cert_serial = fields.Char(
        string='Certificate Serial Number',
        required=True,
        index=True,
        help='Unique serial number of the SSL certificate.'
    )

    user_email = fields.Char(
        string='User Email',
        help='Email address of the user associated with the certificate.'
    )

    ip_address = fields.Char(
        string='IP Address',
        help='Last recorded network address.'
    )

    create_date = fields.Datetime(
        string='Creation Date',
        default=fields.Datetime.now
    )

    update_date = fields.Datetime(
        string='Last Updated',
        default=fields.Datetime.now,
        compute='_compute_update_date',
        store=True
    )

    # ========== Certificate File Fields ==========
    cert_file = fields.Binary(
        string='Certificate File (.p12)',
        attachment=True,
        help='Certificate file in PKCS#12 format.'
    )

    cert_filename = fields.Char(
        string='Filename',
        help='Original filename of the certificate file.'
    )

    # ========== Encrypted Password Fields ==========
    password_encrypted = fields.Char(
        string='Encrypted Password',
        help='Certificate password stored using AES encryption.'
    )

    # Password viewing audit fields
    password_last_viewed = fields.Datetime(
        string='Password Last Viewed'
    )

    password_viewed_by = fields.Many2one(
        'res.users',
        string='Last Viewed By'
    )

    # ========== Status Management Fields ==========
    state = fields.Selection([
        ('draft', 'To Activate'),
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('revoked', 'Revoked')
    ],
    string='Status',
    default='draft',
    required=True,
    index=True
    )

    is_placeholder = fields.Boolean(
        string='Is Placeholder',
        compute='_compute_is_placeholder',
        store=True,
        help='True indicates this record is waiting for first binding.'
    )

    # ========== Related Fields ==========
    mail_log_ids = fields.One2many(
        'device.cert.mail.log',
        'bind_id',
        string='Mail Send Logs'
    )

    status_log_ids = fields.One2many(
        'device.cert.status.log',
        'bind_id',
        string='Status Change Logs'
    )
    last_login=fields.Datetime(string='Last Login')
    
    # ========== Conditional Business Constraints ==========
    @api.constrains('device_id', 'cert_serial', 'is_placeholder')
    def _check_device_cert_unique(self):
        """
        Conditional uniqueness constraint: 
        When is_placeholder=False, enforce uniqueness of (device_id, cert_serial) combination.
        """
        for record in self:
            # Only enforce constraint for non-placeholder records
            if not record.is_placeholder and record.device_id and record.cert_serial:
                # Search for other non-placeholder records with the same combination
                existing = self.search([
                    ('device_id', '=', record.device_id),
                    ('cert_serial', '=', record.cert_serial),
                    ('is_placeholder', '=', False),
                    ('id', '!=', record.id)
                ], limit=1)
                
                if existing:
                    raise ValidationError(
                        _("Device ID '%(device)s' with Certificate Serial '%(cert)s' must be unique for active bindings.") 
                        % {
                            'device': record.device_id,
                            'cert': record.cert_serial
                        }
                    )

    # ========== Computed Fields ==========
    @api.depends('device_id')
    def _compute_is_placeholder(self):
        """Compute whether the record is a placeholder."""
        for record in self:
            record.is_placeholder = not record.device_id or record.device_id == 'PLACEHOLDER_FOR_FIRST_BIND'

    @api.depends('state')
    def _compute_update_date(self):
        """Update the modification date when the state changes."""
        for record in self:
            if record._origin.state != record.state:
                record.update_date = fields.Datetime.now()

    # ========== Constraint Validation ==========
    @api.constrains('cert_serial')
    def _check_cert_serial_format(self):
        """Validate the format of the certificate serial number."""
        for record in self:
            if record.cert_serial and len(record.cert_serial) < 10:
                raise ValidationError(_("Certificate serial number format is incorrect."))

    @api.constrains('device_id')
    def _check_device_id_uniqueness(self):
        """Validate the uniqueness of the Device ID (for non-placeholder cases)."""
        for record in self:
            if record.device_id and record.device_id != 'PLACEHOLDER_FOR_FIRST_BIND':
                existing = self.search([
                    ('device_id', '=', record.device_id),
                    ('id', '!=', record.id)
                ], limit=1)
                if existing:
                    raise ValidationError(
                        _("Device ID %s is already bound to another certificate.") % record.device_id
                    )

    # ========== Key Management Methods ==========

    def _encrypt_password(self, plain_password):
        """Encrypt password using API-style method"""
        tool = self.env['device.cert.encryption.tool']
        return tool.encrypt(plain_password)
    
    def _decrypt_password(self, encrypted_password):
        """Decrypt password using auto-detection"""
        tool = self.env['device.cert.encryption.tool']
        return tool.decrypt_auto(encrypted_password)

    # ========== Business Methods ==========
    def action_send_certificate(self):
        """Send certificate email with attachment and full guide."""
        self.ensure_one()

        if not all([self.user_email, self.cert_file]):
            raise UserError(_("Cannot send email: Missing recipient email or certificate file."))
        
        if not is_valid_email(self.user_email):
            raise UserError(_("Cannot send email: Invalid recipient email."))

        # Find email template
        template = self.env.ref('custom_device_cert.email_template_cert_guide', False)
        if not template:
            raise UserError(_("Email template not found."))

        # Create certificate attachment
        attachment = self.env['ir.attachment'].create({
            'name': self.cert_filename or f'certificate_{self.cert_serial[:8]}.p12',
            'datas': self.cert_file,
            'res_model': 'device.cert.bind',
            'res_id': self.id,
            'type': 'binary',
        })

        try:
            email_values = {
                'attachment_ids': [attachment.id],
                'email_from': self.env.user.email,
                'reply_to': self.env.user.email,
                'email_to': self.user_email,
                'auto_delete': False,
            }
            # Send email with attachment
            template.send_mail(
                self.id,
                force_send=True,
                raise_exception=True,
                email_values=email_values
            )
            

            # Log the send
            self.env['device.cert.mail.log'].create({
                'bind_id': self.id,
                'email': self.user_email,
                'sent_by': self.env.user.id,                
            })

            _logger.info("Certificate email sent to %s (serial: %s)", self.user_email, self.cert_serial)
            return True

        except Exception as e:
            _logger.error("Failed to send certificate email: %s", str(e))
            raise UserError(_("Failed to send email: %s", str(e)))
    def action_view_password(self):
        """
        Show decrypted certificate password in a popup
        Restricted to admin users only
        """
        self.ensure_one()

        # Enhanced Permission check with logging
        if not self.env.user.has_group('base.group_system'):
            _logger.warning(f"Unauthorized access attempt to view password for record {self.id} by user {self.env.user.id}")
            raise UserError(_("Access Denied: Administrator privileges required to view passwords."))
        
        # Additional check: Ensure user is active and not a public user
        if not self.env.user.active or self.env.user.share:
            raise UserError(_("Access Denied: Invalid user account."))
        
        # Rate limiting: Prevent too many password views in short time
        last_view_time = self.password_last_viewed
        if last_view_time:
            time_diff = (fields.Datetime.now() - last_view_time).total_seconds()
            if time_diff < 30:  # Minimum 30 seconds between views
                raise UserError(_("Too many password view attempts. Please wait before trying again."))

        # Validate encrypted data
        if not self.password_encrypted:
            raise UserError(_("No encrypted password found for this certificate."))

        # Decrypt
        password = self._decrypt_password(self.password_encrypted)

        # Show error if decryption failed
        if "[Decryption Error" in password:
            raise UserError(_("Certificate Password\n\n%s") % password)

        # Audit log
        self.write({
            'password_last_viewed': fields.Datetime.now(),
            'password_viewed_by': self.env.user.id
        })

        # Show password
        raise UserError(_("Certificate Password\n\n%s") % password)

    def action_activate(self):
        """Activate the binding."""
        for record in self:
            if record.state != 'active':
                old_state = record.state
                record.state = 'active'

                # Log the status change
                self.env['device.cert.status.log'].create({
                    'bind_id': record.id,
                    'old_state': old_state,
                    'new_state': 'active',
                    'done_by': self.env.user.id,
                })
                _logger.info(f"Binding record {record.id} has been activated.")

    def action_deactivate(self):
        """Deactivate the binding."""
        for record in self:
            if record.state != 'inactive':
                old_state = record.state
                record.state = 'inactive'

                self.env['device.cert.status.log'].create({
                    'bind_id': record.id,
                    'old_state': old_state,
                    'new_state': 'inactive',
                    'done_by': self.env.user.id,
                })
                _logger.info(f"Binding record {record.id} has been deactivated.")

    def action_revoke(self):
        """Revoke the binding (irreversible operation)."""
        self.ensure_one()

        if self.state == 'revoked':
            raise UserError(_("This binding is already revoked."))

        old_state = self.state
        self.state = 'revoked'

        self.env['device.cert.status.log'].create({
            'bind_id': self.id,
            'old_state': old_state,
            'new_state': 'revoked',
            'done_by': self.env.user.id,
            'notes': 'Certificate has been permanently revoked.'
        })

        _logger.warning(f"Binding record {self.id} has been revoked.")

    # ========== Utility Methods ==========

    def find_by_device_and_cert(self, device_id, cert_serial):
        """Find the exact device-certificate binding."""
        return self.search([
            ('device_id', '=', device_id),
            ('cert_serial', '=', cert_serial)
        ], limit=1)

    def find_placeholder_by_cert(self, cert_serial):
        """Find a placeholder record for the specified certificate serial number."""
        return self.search([
            ('cert_serial', '=', cert_serial),
            '|', ('device_id', '=', False),
                 ('device_id', '=', 'PLACEHOLDER_FOR_FIRST_BIND')
        ], limit=1)


class DeviceCertMailLog(models.Model):
    """Sub-model for Mail Sending Logs"""
    _name = 'device.cert.mail.log'
    _description = 'Mail Send Logs'
    _order = 'create_date DESC'

    bind_id = fields.Many2one(
        'device.cert.bind',
        string='Binding Record',
        ondelete='cascade',
        required=True
    )
    email = fields.Char(string='Recipient Email', required=True)
    sent_by = fields.Many2one('res.users', string='Sent By')
    create_date = fields.Datetime(string='Sent On', default=fields.Datetime.now)
    status = fields.Selection([
        ('sent', 'Sent'),
        ('failed', 'Failed')
    ], string='Status', default='sent')


class DeviceCertStatusLog(models.Model):
    """Sub-model for Status Change Logs"""
    _name = 'device.cert.status.log'
    _description = 'Status Change Logs'
    _order = 'create_date DESC'

    bind_id = fields.Many2one(
        'device.cert.bind',
        string='Binding Record',
        ondelete='cascade',
        required=True
    )
    old_state = fields.Char(string='Previous State')
    new_state = fields.Char(string='New State', required=True)
    done_by = fields.Many2one('res.users', string='Operator')
    create_date = fields.Datetime(string='Operation Time', default=fields.Datetime.now)
    notes = fields.Text(string='Notes')