# -*- coding: utf-8 -*-

from . import models
from . import inbound_order
from . import outbound_order
from . import my_stock
from . import my_project
from . import my_product
#from . import my_report
#from . import my_user
from . import waybill
#from . import my_partner
from . import my_picking_type
from . import my_package_barcode
from . import my_api_user
from . import my_location
#from . import my_excel_template
from . import my_product_template
from . import inbound_order_summary
from . import outbound_order_summary
from . import outbound_order_sn_detail
from . import linglong_inbound_temp
from . import product_duplicate
from . import inbound_order_status
from . import outbound_order_status
from . import charge_item
from . import inbound_order_charge
from . import outbound_order_pack_info
from . import outbound_order_charge
from . import my_dashboard