{
    "name": "Qooling Inbound Form",
    "version": "18.0.1.0.0",
    "category": "Operations",
    "summary": "Inbound Form record tool",
    "depends": ["base", "web", "stock"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/inbound_form_views.xml",
        "views/outbound_form_views.xml",
        "views/temperature_record_views.xml",
        "views/dashboard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "wd_qooling_app/static/src/js/signature_field.js",
            "wd_qooling_app/static/src/js/qooling_dashboard.js",
            "wd_qooling_app/static/src/js/pda_record_dashboard.js",
            "wd_qooling_app/static/src/xml/signature_field.xml",
            "wd_qooling_app/static/src/xml/qooling_dashboard.xml",
            "wd_qooling_app/static/src/xml/pda_record_dashboard.xml",
            "wd_qooling_app/static/src/scss/pda_record_dashboard.scss",
            "wd_qooling_app/static/src/js/inbound_pda.js",
            "wd_qooling_app/static/src/js/outbound_pda.js",
            "wd_qooling_app/static/src/js/temperature_pda.js",
            "wd_qooling_app/static/src/js/photo_gallery_field.js",
            "wd_qooling_app/static/src/xml/inbound_pda.xml",
            "wd_qooling_app/static/src/xml/outbound_pda.xml",
            "wd_qooling_app/static/src/xml/temperature_pda.xml",
            "wd_qooling_app/static/src/xml/photo_gallery_field.xml",
            "wd_qooling_app/static/src/scss/inbound_pda.scss",
            "wd_qooling_app/static/src/scss/photo_gallery_field.scss",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
