flowchart TD
    A0[进口]
    A01[换单]
    A02[清关]
    A03[港至仓]
    A04[港至其他]

    A0-->A01
    A0-->A02
    A0-->A03
    A0-->A04

    A1[仓储]
    A11[入库]
    A12[出库]
    A13[库龄*]
    A1-->A11
    A1-->A12
    A1-->A13


    A3[尾程配送]

    A01-->B
    A02-->B
    A03-->B
    A04-->B
    A11-->B
    A12-->B
    A13-->B
    A3-->B

    B[作业*]
    C1[成本记录*]
    B-->C1

    PA[付款申请]
    PB[付款单]

    PV[应付发票]
    PC[成本核对*]
    PC-->PA
    PA-->PB

    PV-->PC
    C1-->PC


    %% 作业产生数量
    B -->|获取数量| E[计算引擎]

    %% 价格来自客户报价单
    C[客户报价单*] -->|获取价格| E

    %% 逻辑来自计算规则/计算逻辑
    D[计算规则] -->|获取逻辑| E
    F[收费记录*]
    %% 引擎计算并生成收费记录
    E -->|计算金额| F
    B -->|手工录入| F


    %% 收费记录汇总到期间对账单
    F --> G[期间对账单]
    G[期间对账单]-->IA[开票申请]-->IV[应收发票]
    RV[收款]
    SV[应收核销*]
    IV-->SV
    RV-->SV

    %% 客户异议：对账后回到收费记录调整/复核
    G -->|客户异议| F
