flowchart TD

%% =========================
%% ① 业务来源（作业入口）
%% =========================
subgraph S0[业务来源]
direction TB

  subgraph S01[进口]
  direction TB
    A0[进口]
    A01[换单]
    A02[清关]
    A03[港至仓]
    A04[港至其他]
    A0 --> A01
    A0 --> A02
    A0 --> A03
    A0 --> A04
  end

  subgraph S02[仓储]
  direction TB
    A1[仓储]
    A11[入库]
    A12[出库]
    A13[库龄*]
    A1 --> A11
    A1 --> A12
    A1 --> A13
  end

  A3[尾程配送]
  A4[其他业务]
end


%% =========================
%% ② 作业入口（公共对象，不放在应收里）
%% =========================
subgraph S4[作业入口]
direction TB
%%  IN((作业入口汇聚))
  B[作业*]


  A01 --> B
  A02 --> B
  A03 --> B
  A04 --> B
  A11 --> B
  A12 --> B
  A13 --> B
  A3  --> B
  A4  --> B

%%  IN --> B

end


%% =========================
%% ③ 成本管理（应付链）
%% =========================
subgraph S1[成本管理（应付）]

direction TB
  C1[成本记录*]
  PC[成本核对*]
  PV[应付发票]
  PA[付款申请]
  PB[付款单]

  B --> C1
  PV --> PC
  C1 --> PC
  PC --> PA --> PB
end


%% =========================
%% ④ 收费管理（应收链）
%% =========================
subgraph S2[收费管理（应收）]
direction TB
  Q[数量来源]
  E[计算引擎]
  P[价格来源]
  R[规则来源]

  C[客户报价单*] --> P
  D[计算规则] --> R
  B --> Q
  Q -->|获取数量| E
  P -->|获取价格| E
  R -->|获取逻辑| E

  F[收费记录*]
  E -->|计算金额| F
  B -->|手工录入| F

  G[期间对账单]
  F --> G

  IA[开票申请]
  IV[应收发票]
  G --> IA --> IV

  RV[收款]
  SV[应收核销*]
  IV --> SV
  RV --> SV

  G -->|客户异议| F
end
