import base64
import io
from datetime import datetime, time, timedelta
from math import ceil

import xlsxwriter

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError


MUTATION_TYPE_SELECTION = [
    ("balance", "Balance"),
    ("inbound", "Inbound"),
    ("outbound", "Outbound"),
    ("finding", "Finding"),
    ("missing", "Missing"),
    ("correction", "Correction"),
    ("total", "Total"),
]

BOND_FLAG_SELECTION = [("true", "Bonded"), ("false", "Non-Bonded")]


class BondedInventoryMovementHistoryReport(models.Model):
    _name = "bonded.inventory.movement.history.report"
    _description = "Inventory Movement History Report"
    _order = "id desc"

    name = fields.Char(string="Report Name", required=True, default="New", copy=False, index=True)
    period_begin = fields.Date(string="Period Begin", required=True, copy=False, index=True)
    period_end = fields.Date(string="Period End", required=True, copy=False, index=True)
    warehouse_id = fields.Many2one("stock.warehouse", string="Warehouse", required=True, copy=False, index=True)
    bonded_flag = fields.Selection(BOND_FLAG_SELECTION, string="Customs Status", copy=False, index=True)
    state = fields.Selection([("draft", "Draft"), ("done", "Done")], string="State", default="draft", required=True, copy=False, index=True)
    generated_at = fields.Datetime(string="Generated At", readonly=True, copy=False, index=True)
    generated_by_id = fields.Many2one("res.users", string="Generated By", readonly=True, copy=False, index=True)
    opening_total_qty = fields.Float(string="Opening Total Qty", readonly=True, copy=False)
    inbound_total_qty = fields.Float(string="Inbound Total Qty", readonly=True, copy=False)
    outbound_total_qty = fields.Float(string="Outbound Total Qty", readonly=True, copy=False)
    finding_total_qty = fields.Float(string="Finding Total Qty", readonly=True, copy=False)
    missing_total_qty = fields.Float(string="Missing Total Qty", readonly=True, copy=False)
    correction_total_qty = fields.Float(string="Correction Total Qty", readonly=True, copy=False)
    closing_total_qty = fields.Float(string="Closing Total Qty", readonly=True, copy=False)
    total_gross_weight = fields.Float(string="Total Gross Weight (kg)", readonly=True, copy=False)
    total_net_weight = fields.Float(string="Total Net Weight (kg)", readonly=True, copy=False)
    movement_lines = fields.One2many("bonded.inventory.movement.history.report.line", "report_id", string="Movement Lines", copy=False)

    def action_open_export_lines(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Inventory Movement Lines"),
            "res_model": "bonded.inventory.movement.history.report.line",
            "view_mode": "list,form",
            "views": [
                (self.env.ref("bonded_mange.view_inventory_movement_history_report_line_export_list").id, "list")],
            "search_view_id": self.env.ref(
                "bonded_mange.view_inventory_movement_history_report_line_export_search"
            ).id,
            "domain": [("report_id", "=", self.id)],
            "context": {
                "default_report_id": self.id,
                "inventory_movement_history_report_id": self.id,
            },
            "target": "current",
        }

    def action_print_excel(self):
        action = False
        attachment_model = self.env["ir.attachment"]

        for rec in self:
            if rec.state != "done":
                raise ValidationError(_("Please query the report before printing Excel."))

            output = io.BytesIO()
            workbook = xlsxwriter.Workbook(output, {"in_memory": True})
            worksheet = workbook.add_worksheet("Inventory Movement")
            info_label_format = workbook.add_format({"bold": True})
            info_value_format = workbook.add_format({})
            info_number_format = workbook.add_format({"num_format": "0.00"})
            header_format = workbook.add_format({
                "bold": True,
                "align": "center",
                "valign": "vcenter",
                "bg_color": "#F1F1F1",
                "border": 1,
            })
            cell_format = workbook.add_format({"border": 1, "valign": "vcenter"})
            number_format = workbook.add_format({
                "border": 1,
                "valign": "vcenter",
                "align": "right",
                "num_format": "0.00",
            })
            total_cell_format = workbook.add_format({
                "bold": True,
                "border": 1,
                "valign": "vcenter",
                "bg_color": "#595959",
                "font_color": "#FFFFFF",
            })
            total_number_format = workbook.add_format({
                "bold": True,
                "border": 1,
                "valign": "vcenter",
                "align": "right",
                "num_format": "0.00",
                "bg_color": "#595959",
                "font_color": "#FFFFFF",
            })

            bonded_label_map = dict(BOND_FLAG_SELECTION)
            mutation_label_map = dict(MUTATION_TYPE_SELECTION)
            generated_at_text = ""
            if rec.generated_at:
                generated_at_text = fields.Datetime.context_timestamp(
                    rec, rec.generated_at
                ).strftime("%Y-%m-%d %H:%M:%S")

            left_info_list = [
                ("Report Name", rec.name or ""),
                ("Period Begin", fields.Date.to_string(rec.period_begin) if rec.period_begin else ""),
                ("Period End", fields.Date.to_string(rec.period_end) if rec.period_end else ""),
                ("Warehouse", rec.warehouse_id.display_name if rec.warehouse_id else ""),
                ("Customs Status", bonded_label_map.get(rec.bonded_flag, "All")),
            ]
            right_info_list = [
                ("Generated At", generated_at_text),
                ("Generated By", rec.generated_by_id.name if rec.generated_by_id else ""),
                ("Opening Total Qty", rec.opening_total_qty or 0.0),
                ("Inbound Total Qty", rec.inbound_total_qty or 0.0),
                ("Outbound Total Qty", rec.outbound_total_qty or 0.0),
                ("Finding Total Qty", rec.finding_total_qty or 0.0),
                ("Missing Total Qty", rec.missing_total_qty or 0.0),
                ("Correction Total Qty", rec.correction_total_qty or 0.0),
                ("Closing Total Qty", rec.closing_total_qty or 0.0),
                ("Total Gross Weight (kg)", rec.total_gross_weight or 0.0),
                ("Total Net Weight (kg)", rec.total_net_weight or 0.0),
            ]
            for row_index, (label, value) in enumerate(left_info_list):
                worksheet.write(row_index, 0, label, info_label_format)
                worksheet.write(row_index, 1, value, info_value_format)
            for row_index, (label, value) in enumerate(right_info_list):
                worksheet.write(row_index, 2, label, info_label_format)
                if isinstance(value, (int, float)):
                    worksheet.write_number(row_index, 3, value, info_number_format)
                else:
                    worksheet.write(row_index, 3, value, info_value_format)

            header_row = 11
            header_list = [
                "Product Name (SKU)",
                "Product Description",
                "Marks/Article No./Tech Desc.",
                "Commodity Code",
                "Period Begin",
                "Period End",
                "Begin Stock Date",
                "Begin Stock Qty",
                "Date of Mutation",
                "Mutation Type",
                "Inbound/Outbound No.",
                "Unique Identifier",
                "Corresponding MRN",
                "Customs Status",
                "Kind of Colli",
                "Mutation Quantity",
                "Gross Weight (kg)",
                "Net Weight (kg)",
                "End Stock Date",
                "End Stock Qty",
            ]
            worksheet.write_row(header_row, 0, header_list, header_format)
            worksheet.freeze_panes(header_row + 1, 0)
            column_width_list = [
                30, 30, 34, 20, 14, 14, 16, 16, 16, 18,
                22, 22, 22, 16, 18, 18, 20, 18, 16, 16,
            ]
            for column_index, width in enumerate(column_width_list):
                worksheet.set_column(column_index, column_index, width)

            line_list = rec.movement_lines.sorted(
                key=lambda line: (line.sequence, line.id)
            )
            for row_index, line in enumerate(line_list, start=header_row + 1):
                line_cell_format = total_cell_format if line.mutation_type == "total" else cell_format
                line_number_format = total_number_format if line.mutation_type == "total" else number_format
                worksheet.write(row_index, 0, line.product_id.display_name or "", line_cell_format)
                worksheet.write(row_index, 1, line.product_description or "", line_cell_format)
                worksheet.write(row_index, 2, line.marks_article_technical_description or "", line_cell_format)
                worksheet.write(row_index, 3, line.commodity_code or "", line_cell_format)
                worksheet.write(row_index, 4, fields.Date.to_string(line.period_begin) if line.period_begin else "", line_cell_format)
                worksheet.write(row_index, 5, fields.Date.to_string(line.period_end) if line.period_end else "", line_cell_format)
                worksheet.write(row_index, 6, fields.Date.to_string(line.begin_stock_date) if line.begin_stock_date else "", line_cell_format)
                worksheet.write_number(row_index, 7, line.begin_stock_qty or 0.0, line_number_format)
                worksheet.write(row_index, 8, fields.Date.to_string(line.date_of_mutation) if line.date_of_mutation else "", line_cell_format)
                worksheet.write(row_index, 9, mutation_label_map.get(line.mutation_type, ""), line_cell_format)
                worksheet.write(row_index, 10, line.inbound_outbound_number or "", line_cell_format)
                worksheet.write(row_index, 11, line.unique_identifier or "", line_cell_format)
                worksheet.write(row_index, 12, line.mrn_id.code if line.mrn_id else "", line_cell_format)
                worksheet.write(row_index, 13, bonded_label_map.get(line.bonded_flag, ""), line_cell_format)
                worksheet.write(row_index, 14, line.kind_of_colli or "", line_cell_format)
                worksheet.write_number(row_index, 15, line.mutation_quantity or 0.0, line_number_format)
                worksheet.write_number(row_index, 16, line.gross_weight or 0.0, line_number_format)
                worksheet.write_number(row_index, 17, line.net_weight or 0.0, line_number_format)
                worksheet.write(row_index, 18, fields.Date.to_string(line.end_stock_date) if line.end_stock_date else "", line_cell_format)
                worksheet.write_number(row_index, 19, line.end_stock_qty or 0.0, line_number_format)

            if line_list:
                worksheet.autofilter(
                    header_row,
                    0,
                    header_row + len(line_list),
                    len(header_list) - 1,
                )

            workbook.close()
            output.seek(0)
            attachment = attachment_model.create({
                "name": "Inventory_Movement_History_%s.xlsx" % (rec.name or rec.id),
                "type": "binary",
                "datas": base64.b64encode(output.read()),
                "res_model": rec._name,
                "res_id": rec.id,
                "mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            })
            action = {
                "type": "ir.actions.act_url",
                "url": "/web/content/%s?download=true" % attachment.id,
                "target": "self",
            }

        return action

    def action_query_movement_history(self):
        move_line_model = self.env["stock.move.line"]
        location_model = self.env["stock.location"]
        product_model = self.env["product.product"]
        product_uom_model = self.env["uom.uom"]
        report_line_model = self.env["bonded.inventory.movement.history.report.line"]

        for rec in self:
            if rec.state != "draft":
                raise ValidationError(_("A generated report is locked. Please create a new report to query again."))
            if rec.period_begin > rec.period_end:
                raise ValidationError(_("Period Begin cannot be later than Period End."))
            if not rec.warehouse_id.view_location_id:
                raise ValidationError(_("The selected warehouse must have a stock location."))

            period_begin_datetime = datetime.combine(rec.period_begin, time.min)
            period_end_datetime = datetime.combine(rec.period_end + timedelta(days=1), time.min)
            warehouse_location_ids = location_model.sudo().search([
                ("id", "child_of", rec.warehouse_id.view_location_id.id),
            ]).ids
            if not warehouse_location_ids:
                raise ValidationError(_("No locations were found under the selected warehouse."))

            # Opening balances are aggregated in PostgreSQL so historical move lines are not loaded one by one.
            opening_bonded_filter_sql = ""
            opening_query_params = [warehouse_location_ids, period_begin_datetime]
            if rec.bonded_flag:
                opening_bonded_filter_sql = """
                    AND COALESCE(NULLIF(sml.bonded_flag, ''), 'false') = %s
                """
                opening_query_params.append(rec.bonded_flag)

            opening_query = f"""
                WITH warehouse_location AS (
                    SELECT UNNEST(%s::integer[]) AS id
                )
                SELECT
                    sml.product_id,
                    COALESCE(NULLIF(sml.bonded_flag, ''), 'false') AS bonded_flag,
                    COALESCE(
                        NULLIF(BTRIM(sml.unique_identifier), ''),
                        NULLIF(BTRIM(sm.unique_identifier), ''),
                        NULLIF(BTRIM(sp.unique_identifier), ''),
                        ''
                    ) AS unique_identifier,
                    sml.product_uom_id,
                    SUM(
                        CASE
                            WHEN sm.customs_mutation_type = 'inbound'
                                 AND sml.location_dest_id IN (SELECT id FROM warehouse_location)
                                 AND sml.location_id NOT IN (SELECT id FROM warehouse_location)
                            THEN ABS(sml.quantity)
                            WHEN sm.customs_mutation_type = 'outbound'
                                 AND sml.location_id IN (SELECT id FROM warehouse_location)
                                 AND sml.location_dest_id NOT IN (SELECT id FROM warehouse_location)
                            THEN -ABS(sml.quantity)
                            WHEN sm.customs_mutation_type = 'finding'
                                 AND (
                                     (sml.location_id IN (SELECT id FROM warehouse_location)
                                      AND sml.location_dest_id NOT IN (SELECT id FROM warehouse_location))
                                     OR
                                     (sml.location_dest_id IN (SELECT id FROM warehouse_location)
                                      AND sml.location_id NOT IN (SELECT id FROM warehouse_location))
                                 )
                            THEN ABS(sml.quantity)
                            WHEN sm.customs_mutation_type = 'missing'
                                 AND (
                                     (sml.location_id IN (SELECT id FROM warehouse_location)
                                      AND sml.location_dest_id NOT IN (SELECT id FROM warehouse_location))
                                     OR
                                     (sml.location_dest_id IN (SELECT id FROM warehouse_location)
                                      AND sml.location_id NOT IN (SELECT id FROM warehouse_location))
                                 )
                            THEN -ABS(sml.quantity)
                            WHEN sm.customs_mutation_type = 'correction'
                                 AND sml.location_dest_id IN (SELECT id FROM warehouse_location)
                                 AND sml.location_id NOT IN (SELECT id FROM warehouse_location)
                            THEN ABS(sml.quantity)
                            WHEN sm.customs_mutation_type = 'correction'
                                 AND sml.location_id IN (SELECT id FROM warehouse_location)
                                 AND sml.location_dest_id NOT IN (SELECT id FROM warehouse_location)
                            THEN -ABS(sml.quantity)
                            ELSE 0
                        END
                    ) AS opening_qty
                FROM stock_move_line sml
                JOIN stock_move sm ON sm.id = sml.move_id
                LEFT JOIN stock_picking sp ON sp.id = sml.picking_id
                WHERE sml.state = 'done'
                    AND sml.date < %s
                    AND sml.product_id IS NOT NULL
                    AND sml.quantity <> 0
                    AND sm.customs_mutation_type IS NOT NULL
                    AND (
                        (sm.customs_mutation_type = 'inbound'
                         AND sml.location_dest_id IN (SELECT id FROM warehouse_location)
                         AND sml.location_id NOT IN (SELECT id FROM warehouse_location))
                        OR
                        (sm.customs_mutation_type = 'outbound'
                         AND sml.location_id IN (SELECT id FROM warehouse_location)
                         AND sml.location_dest_id NOT IN (SELECT id FROM warehouse_location))
                        OR
                        (sm.customs_mutation_type IN ('finding', 'missing', 'correction')
                         AND (
                             (sml.location_id IN (SELECT id FROM warehouse_location)
                              AND sml.location_dest_id NOT IN (SELECT id FROM warehouse_location))
                             OR
                             (sml.location_dest_id IN (SELECT id FROM warehouse_location)
                              AND sml.location_id NOT IN (SELECT id FROM warehouse_location))
                         ))
                    )
                    {opening_bonded_filter_sql}
                GROUP BY
                    sml.product_id,
                    COALESCE(NULLIF(sml.bonded_flag, ''), 'false'),
                    COALESCE(
                        NULLIF(BTRIM(sml.unique_identifier), ''),
                        NULLIF(BTRIM(sm.unique_identifier), ''),
                        NULLIF(BTRIM(sp.unique_identifier), ''),
                        ''
                    ),
                    sml.product_uom_id
            """
            self.env.cr.execute(opening_query, opening_query_params)
            opening_row_list = self.env.cr.fetchall()

            movement_domain = [
                ("state", "=", "done"),
                ("date", ">=", period_begin_datetime),
                ("date", "<", period_end_datetime),
                ("move_id.customs_mutation_type", "!=", False),
                "|",
                ("location_id", "in", warehouse_location_ids),
                ("location_dest_id", "in", warehouse_location_ids),
            ]
            if rec.bonded_flag:
                movement_domain.append(("bonded_flag", "=", rec.bonded_flag))
            move_line_list = move_line_model.sudo().search(movement_domain, order="date asc, id asc")

            opening_product_id_list = [row[0] for row in opening_row_list if row[0]]
            opening_product_map = {
                product.id: product
                for product in product_model.sudo().browse(opening_product_id_list).exists()
            }
            opening_product_uom_id_list = [row[3] for row in opening_row_list if row[3]]
            opening_product_uom_map = {
                product_uom.id: product_uom
                for product_uom in product_uom_model.sudo().browse(opening_product_uom_id_list).exists()
            }

            group_map = {}
            for product_id, bonded_flag, unique_identifier, product_uom_id, opening_qty in opening_row_list:
                product = opening_product_map.get(product_id)
                if not product:
                    continue
                product_uom = opening_product_uom_map.get(product_uom_id) or product.uom_id
                group_key = (product.id, bonded_flag, unique_identifier, product_uom.id)
                group_map[group_key] = {
                    "product": product,
                    "bonded_flag": bonded_flag,
                    "unique_identifier": unique_identifier,
                    "product_uom_id": product_uom.id,
                    "kind_of_colli": product_uom.name,
                    "opening_qty": float(opening_qty or 0.0),
                    "event_map": {},
                }

            warehouse_location_id_set = set(warehouse_location_ids)

            for move_line in move_line_list:
                quantity = abs(move_line.quantity or 0.0)
                if not quantity or not move_line.product_id:
                    continue

                source_is_in_warehouse = move_line.location_id.id in warehouse_location_id_set
                destination_is_in_warehouse = move_line.location_dest_id.id in warehouse_location_id_set
                customs_mutation_type = move_line.move_id.customs_mutation_type
                if not customs_mutation_type:
                    continue
                mutation_type = False
                mutation_quantity = 0.0

                if customs_mutation_type == "inbound" and destination_is_in_warehouse and not source_is_in_warehouse:
                    mutation_type = "inbound"
                    mutation_quantity = quantity
                elif customs_mutation_type == "outbound" and source_is_in_warehouse and not destination_is_in_warehouse:
                    mutation_type = "outbound"
                    mutation_quantity = -quantity
                elif source_is_in_warehouse != destination_is_in_warehouse:
                    mutation_type = customs_mutation_type
                    if mutation_type == "finding":
                        mutation_quantity = quantity
                    elif mutation_type == "missing":
                        mutation_quantity = -quantity
                    elif mutation_type == "correction":
                        mutation_quantity = quantity if destination_is_in_warehouse else -quantity
                    else:
                        continue
                else:
                    continue

                unique_identifier = (move_line.unique_identifier or move_line.move_id.unique_identifier or move_line.picking_id.unique_identifier or "").strip()
                bonded_flag = move_line.bonded_flag if move_line.bonded_flag in ("true", "false") else "false"
                if rec.bonded_flag and bonded_flag != rec.bonded_flag:
                    continue
                product_uom = move_line.product_uom_id or move_line.move_id.product_uom or move_line.product_id.uom_id
                group_key = (move_line.product_id.id, bonded_flag, unique_identifier, product_uom.id)
                group_data = group_map.setdefault(group_key, {
                    "product": move_line.product_id,
                    "bonded_flag": bonded_flag,
                    "unique_identifier": unique_identifier,
                    "product_uom_id": product_uom.id,
                    "kind_of_colli": product_uom.name,
                    "opening_qty": 0.0,
                    "event_map": {},
                })

                move_datetime = fields.Datetime.to_datetime(move_line.date)
                if not move_datetime:
                    continue
                net_weight = quantity * (move_line.product_id.weight or 0.0)
                packaging = move_line.move_id.product_packaging_id
                estimated_package_weight = packaging.estimated_package_weight if packaging else 0.0
                package_count = ceil(quantity / packaging.qty) if packaging and packaging.qty else 0
                gross_weight = net_weight + (package_count * estimated_package_weight)
                if mutation_quantity < 0:
                    net_weight = -net_weight
                    gross_weight = -gross_weight

                kind_of_colli = product_uom.name

                inbound_outbound_number = False
                if move_line.inbound_order_id:
                    inbound_outbound_number = move_line.inbound_order_id.billno
                elif move_line.outbound_order_id:
                    inbound_outbound_number = move_line.outbound_order_id.billno

                if mutation_type == "outbound" and move_line.outbound_order_id:
                    event_key = (
                        "outbound",
                        move_line.outbound_order_id.id,
                        move_line.mrn_id.id or False,
                    )
                else:
                    event_key = ("move_line", move_line.id)

                event_data = group_data["event_map"].get(event_key)
                if event_data:
                    event_data["mutation_quantity"] += mutation_quantity
                    event_data["gross_weight"] += gross_weight
                    event_data["net_weight"] += net_weight
                    if not event_data["kind_of_colli"] and kind_of_colli:
                        event_data["kind_of_colli"] = kind_of_colli
                else:
                    group_data["event_map"][event_key] = {
                        "source_move_line_id": move_line.id,
                        "date": move_datetime.date(),
                        "mutation_type": mutation_type,
                        "mutation_quantity": mutation_quantity,
                        "inbound_outbound_number": inbound_outbound_number or False,
                        "mrn_id": move_line.mrn_id.id or False,
                        "kind_of_colli": kind_of_colli or False,
                        "gross_weight": gross_weight,
                        "net_weight": net_weight,
                    }

            line_vals_list = []
            sequence = 1
            opening_total_qty = 0.0
            inbound_total_qty = 0.0
            outbound_total_qty = 0.0
            finding_total_qty = 0.0
            missing_total_qty = 0.0
            correction_total_qty = 0.0
            closing_total_qty = 0.0
            total_gross_weight = 0.0
            total_net_weight = 0.0
            summary_data_map = {}

            group_data_list = sorted(group_map.values(), key=lambda item: (
                item["product"].default_code or item["product"].display_name or "",
                item["bonded_flag"],
                item["kind_of_colli"],
                item["unique_identifier"],
            ))
            for group_index, group_data in enumerate(group_data_list):
                product = group_data["product"]
                opening_qty = group_data["opening_qty"]
                running_qty = opening_qty
                summary_key = (product.id, group_data["bonded_flag"], group_data["product_uom_id"])
                summary_data = summary_data_map.setdefault(summary_key, {
                    "product": product,
                    "bonded_flag": group_data["bonded_flag"],
                    "product_uom_id": group_data["product_uom_id"],
                    "kind_of_colli": group_data["kind_of_colli"],
                    "opening_qty": 0.0,
                    "mutation_quantity": 0.0,
                    "gross_weight": 0.0,
                    "net_weight": 0.0,
                    "closing_qty": 0.0,
                })
                summary_data["opening_qty"] += opening_qty
                base_vals = {
                    "report_id": rec.id,
                    "product_id": product.id,
                    "product_description": product.product_description or False,
                    "marks_article_technical_description": "/".join(filter(None, [product.article_number, product.technical_description])) or False,
                    "commodity_code": product.hs_code or False,
                    "period_begin": rec.period_begin,
                    "period_end": rec.period_end,
                    "unique_identifier": group_data["unique_identifier"] or False,
                    "bonded_flag": group_data["bonded_flag"],
                    "product_uom_id": group_data["product_uom_id"],
                    "kind_of_colli": group_data["kind_of_colli"],
                }
                line_vals_list.append({
                    **base_vals,
                    "sequence": sequence,
                    "begin_stock_date": rec.period_begin,
                    "begin_stock_qty": opening_qty,
                    "date_of_mutation": rec.period_begin,
                    "mutation_type": "balance",
                    "end_stock_date": rec.period_begin,
                    "end_stock_qty": opening_qty,
                })
                sequence += 1
                opening_total_qty += opening_qty

                event_data_list = sorted(
                    group_data["event_map"].values(),
                    key=lambda item: (item["date"], item["source_move_line_id"]),
                )
                for event_data in event_data_list:
                    begin_qty = running_qty
                    running_qty += event_data["mutation_quantity"]
                    line_vals_list.append({
                        **base_vals,
                        "sequence": sequence,
                        "source_move_line_id": event_data["source_move_line_id"],
                        "begin_stock_date": event_data["date"],
                        "begin_stock_qty": begin_qty,
                        "date_of_mutation": event_data["date"],
                        "mutation_type": event_data["mutation_type"],
                        "inbound_outbound_number": event_data["inbound_outbound_number"],
                        "mrn_id": event_data["mrn_id"],
                        "kind_of_colli": event_data["kind_of_colli"],
                        "mutation_quantity": event_data["mutation_quantity"],
                        "gross_weight": event_data["gross_weight"],
                        "net_weight": event_data["net_weight"],
                        "end_stock_date": event_data["date"],
                        "end_stock_qty": running_qty,
                    })
                    sequence += 1
                    if event_data["mutation_type"] == "inbound":
                        inbound_total_qty += event_data["mutation_quantity"]
                    elif event_data["mutation_type"] == "outbound":
                        outbound_total_qty += abs(event_data["mutation_quantity"])
                    elif event_data["mutation_type"] == "finding":
                        finding_total_qty += event_data["mutation_quantity"]
                    elif event_data["mutation_type"] == "missing":
                        missing_total_qty += abs(event_data["mutation_quantity"])
                    elif event_data["mutation_type"] == "correction":
                        correction_total_qty += event_data["mutation_quantity"]
                    total_gross_weight += event_data["gross_weight"]
                    total_net_weight += event_data["net_weight"]
                    summary_data["mutation_quantity"] += event_data["mutation_quantity"]
                    summary_data["gross_weight"] += event_data["gross_weight"]
                    summary_data["net_weight"] += event_data["net_weight"]

                line_vals_list.append({
                    **base_vals,
                    "sequence": sequence,
                    "begin_stock_date": rec.period_end,
                    "begin_stock_qty": running_qty,
                    "date_of_mutation": rec.period_end,
                    "mutation_type": "balance",
                    "end_stock_date": rec.period_end,
                    "end_stock_qty": running_qty,
                })
                sequence += 1
                closing_total_qty += running_qty
                summary_data["closing_qty"] += running_qty

                next_group_data = group_data_list[group_index + 1] if group_index + 1 < len(group_data_list) else False
                next_summary_key = False
                if next_group_data:
                    next_summary_key = (
                        next_group_data["product"].id,
                        next_group_data["bonded_flag"],
                        next_group_data["product_uom_id"],
                    )
                if next_summary_key != summary_key:
                    line_vals_list.append({
                        "report_id": rec.id,
                        "product_id": summary_data["product"].id,
                        "product_description": summary_data["product"].product_description or False,
                        "marks_article_technical_description": "/".join(filter(None, [summary_data["product"].article_number, summary_data["product"].technical_description])) or False,
                        "commodity_code": summary_data["product"].hs_code or False,
                        "period_begin": rec.period_begin,
                        "period_end": rec.period_end,
                        "bonded_flag": summary_data["bonded_flag"],
                        "product_uom_id": summary_data["product_uom_id"],
                        "kind_of_colli": summary_data["kind_of_colli"],
                        "sequence": sequence,
                        "begin_stock_date": rec.period_begin,
                        "begin_stock_qty": summary_data["opening_qty"],
                        "date_of_mutation": rec.period_end,
                        "mutation_type": "total",
                        "mutation_quantity": summary_data["mutation_quantity"],
                        "gross_weight": summary_data["gross_weight"],
                        "net_weight": summary_data["net_weight"],
                        "end_stock_date": rec.period_end,
                        "end_stock_qty": summary_data["closing_qty"],
                    })
                    sequence += 1

            if line_vals_list:
                report_line_model.with_context(allow_inventory_movement_history_generation=True).create(line_vals_list)
            rec.write({
                "state": "done",
                "generated_at": fields.Datetime.now(),
                "generated_by_id": self.env.user.id,
                "opening_total_qty": opening_total_qty,
                "inbound_total_qty": inbound_total_qty,
                "outbound_total_qty": outbound_total_qty,
                "finding_total_qty": finding_total_qty,
                "missing_total_qty": missing_total_qty,
                "correction_total_qty": correction_total_qty,
                "closing_total_qty": closing_total_qty,
                "total_gross_weight": total_gross_weight,
                "total_net_weight": total_net_weight,
            })
        return True

    def write(self, vals):
        for rec in self:
            if rec.state == "done":
                raise ValidationError(_("Generated inventory movement history reports are locked."))
        return super().write(vals)

    def unlink(self):
        for rec in self:
            if rec.state == "done":
                raise ValidationError(_("Generated inventory movement history reports cannot be deleted."))
        return super().unlink()


class BondedInventoryMovementHistoryReportLine(models.Model):
    _name = "bonded.inventory.movement.history.report.line"
    _description = "Inventory Movement History Report Line"
    _order = "id desc"

    report_id = fields.Many2one("bonded.inventory.movement.history.report", string="Report", required=True, ondelete="cascade", copy=False, index=True)
    sequence = fields.Integer(string="Sequence", required=True, readonly=True, copy=False, index=True)
    source_move_line_id = fields.Many2one("stock.move.line", string="Source Move Line", readonly=True, copy=False, index=True)
    product_id = fields.Many2one("product.product", string="Product Name (SKU)", required=True, readonly=True, copy=False, index=True)
    product_uom_id = fields.Many2one("uom.uom", string="Product UoM", readonly=True, copy=False, index=True)
    product_description = fields.Char(string="Product Description", readonly=True, copy=False)
    marks_article_technical_description = fields.Text(string="Marks/Article No./Tech Desc.", readonly=True, copy=False)
    commodity_code = fields.Char(string="Commodity Code", readonly=True, copy=False, index=True)
    period_begin = fields.Date(string="Period Begin", required=True, readonly=True, copy=False, index=True)
    period_end = fields.Date(string="Period End", required=True, readonly=True, copy=False, index=True)
    begin_stock_date = fields.Date(string="Begin Stock Date", readonly=True, copy=False, index=True)
    begin_stock_qty = fields.Float(string="Begin Stock Qty", readonly=True, copy=False)
    date_of_mutation = fields.Date(string="Date of Mutation", readonly=True, copy=False, index=True)
    mutation_type = fields.Selection(MUTATION_TYPE_SELECTION, string="Mutation Type", readonly=True, copy=False, index=True)
    inbound_outbound_number = fields.Char(string="Inbound/Outbound No.", readonly=True, copy=False, index=True)
    unique_identifier = fields.Char(string="Unique Identifier", readonly=True, copy=False, index=True)
    mrn_id = fields.Many2one("bonded.mrn.master", string="Corresponding MRN", readonly=True, copy=False, index=True)
    bonded_flag = fields.Selection(BOND_FLAG_SELECTION, string="Customs Status", required=True, readonly=True, copy=False, index=True)
    kind_of_colli = fields.Char(string="Kind of Colli", readonly=True, copy=False)
    mutation_quantity = fields.Float(string="Mutation Quantity", readonly=True, copy=False)
    gross_weight = fields.Float(string="Gross Weight (kg)", readonly=True, copy=False)
    net_weight = fields.Float(string="Net Weight (kg)", readonly=True, copy=False)
    end_stock_date = fields.Date(string="End Stock Date", readonly=True, copy=False, index=True)
    end_stock_qty = fields.Float(string="End Stock Qty", readonly=True, copy=False)
    bonded_flag_again = fields.Selection(BOND_FLAG_SELECTION, string="Customs Status Again", related='bonded_flag', store=True, copy=False)

    @api.model_create_multi
    def create(self, vals_list):
        if not self.env.context.get("allow_inventory_movement_history_generation"):
            raise ValidationError(_("Inventory movement history lines can only be generated by the report query."))
        return super().create(vals_list)

    def write(self, vals):
        raise ValidationError(_("Inventory movement history lines are read-only."))

    def unlink(self):
        raise ValidationError(_("Inventory movement history lines cannot be deleted."))
